import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Sparkles, Wind, Flame, Snowflake, RotateCcw, Volume2, VolumeX} from 'lucide-react';
import './style.css';

const MAGES=[
  {id:'mara',name:'Mara Quill',title:'The Briar Scribe',color:'#b7e35c',spell:'Thornbolt',desc:'Fast shots. Defeated shades sprout healing beans.',icon:'✣'},
  {id:'orlo',name:'Orlo Fenn',title:'The Ember Cook',color:'#ff7954',spell:'Cinder Pea',desc:'Heavy fire orbs. Beans briefly increase damage.',icon:'☼'},
  {id:'siv',name:'Siv of the Rime',title:'The Glass Gardener',color:'#76d9e8',spell:'Frost Seed',desc:'Chilling bolts slow enemies and sharpen dodges.',icon:'❉'}
];

function tone(kind,enabled){if(!enabled)return;const A=window.AudioContext||window.webkitAudioContext,a=tone.ctx||(tone.ctx=new A()),o=a.createOscillator(),g=a.createGain(),now=a.currentTime;const set={cast:[mageFreq(kind),.055,'triangle'],hit:[90,.09,'square'],hurt:[55,.28,'sawtooth'],bean:[660,.16,'sine'],dash:[180,.12,'triangle'],wave:[330,.5,'sine']}[kind]||[220,.1,'sine'];o.type=set[2];o.frequency.setValueAtTime(set[0],now);o.frequency.exponentialRampToValueAtTime(Math.max(30,set[0]*(kind==='cast'?1.8:.55)),now+set[1]);g.gain.setValueAtTime(kind==='hurt'?.09:.045,now);g.gain.exponentialRampToValueAtTime(.0001,now+set[1]);o.connect(g).connect(a.destination);o.start();o.stop(now+set[1])}
function mageFreq(){return 260}

function Game({mage,onExit,sound,setSound}){
 const canvas=useRef(), game=useRef(), keys=useRef({}), [hud,setHud]=useState({hp:100,beans:0,wave:1,spell:mage.spell,dead:false,won:false,dash:100,flash:''});
 useEffect(()=>{
  const c=canvas.current,x=c.getContext('2d'); let raf,last=performance.now();
  const g=game.current={p:{x:450,y:310,hp:100,cd:0,dash:0,inv:0},shots:[],enemies:[],beans:[],particles:[],wave:1,kills:0,mouse:{x:700,y:300},over:false,shake:0,hitstop:0,time:0,banner:1.8};
  const burst=(px,py,color,count=8)=>{for(let i=0;i<count;i++){let a=Math.random()*7,s=40+Math.random()*150;g.particles.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,max:.6,color})}};
  const spawn=()=>{g.banner=1.8;tone('wave',sound);for(let i=0;i<4+g.wave*2;i++){let a=Math.random()*Math.PI*2,r=250+Math.random()*120;g.enemies.push({x:450+Math.cos(a)*r,y:310+Math.sin(a)*r,hp:2+g.wave*.4,max:2+g.wave*.4,r:13+Math.random()*7,hit:0,pulse:Math.random()*6,wind:0})}};spawn();
  const kd=e=>{keys.current[e.key.toLowerCase()]=true;if(e.code==='Space'){e.preventDefault();let p=g.p;if(p.dash<=0){p.dash=2.2;p.inv=.38;let dx=(keys.current.d?1:0)-(keys.current.a?1:0),dy=(keys.current.s?1:0)-(keys.current.w?1:0);if(!dx&&!dy){dx=g.mouse.x-p.x;dy=g.mouse.y-p.y}let n=Math.hypot(dx,dy)||1;burst(p.x,p.y,mage.color,12);p.x+=dx/n*92;p.y+=dy/n*92;g.shake=5;tone('dash',sound)}}};
  const ku=e=>keys.current[e.key.toLowerCase()]=false;
  const mm=e=>{let r=c.getBoundingClientRect();g.mouse={x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};
  const shoot=()=>{if(g.over||g.p.cd>0)return;let dx=g.mouse.x-g.p.x,dy=g.mouse.y-g.p.y,n=Math.hypot(dx,dy),a=Math.atan2(dy,dx),count=g.wave>=3?3:1;for(let i=0;i<count;i++){let q=a+(i-(count-1)/2)*.13;g.shots.push({x:g.p.x,y:g.p.y,px:g.p.x,py:g.p.y,vx:Math.cos(q)*520,vy:Math.sin(q)*520,life:1.3})}burst(g.p.x+Math.cos(a)*20,g.p.y+Math.sin(a)*20,mage.color,5);g.p.cd=mage.id==='orlo'?.38:.22;g.shake=2;tone('cast',sound)};
  addEventListener('keydown',kd);addEventListener('keyup',ku);c.addEventListener('mousemove',mm);c.addEventListener('mousedown',shoot);
  function step(t){let dt=Math.min((t-last)/1000,.033);last=t;g.time+=dt;g.banner-=dt;if(g.hitstop>0){g.hitstop-=dt;draw(x,g,mage);raf=requestAnimationFrame(step);return}let p=g.p;if(!g.over){
    p.cd-=dt;p.dash-=dt;p.inv-=dt;let dx=(keys.current.d?1:0)-(keys.current.a?1:0),dy=(keys.current.s?1:0)-(keys.current.w?1:0),n=Math.hypot(dx,dy)||1;p.x=Math.max(35,Math.min(865,p.x+dx/n*190*dt));p.y=Math.max(55,Math.min(575,p.y+dy/n*190*dt));
    g.shots.forEach(s=>{s.px=s.x;s.py=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt});
    g.enemies.forEach(e=>{let dx=p.x-e.x,dy=p.y-e.y,n=Math.hypot(dx,dy);e.pulse+=dt;e.wind=n<90?Math.min(1,e.wind+dt*2.4):Math.max(0,e.wind-dt*3);let pace=e.wind>.75?0:1;e.x+=dx/n*(52+g.wave*5)*dt*pace;e.y+=dy/n*(52+g.wave*5)*dt*pace;e.hit-=dt;if(n<e.r+14&&e.wind>.82&&p.inv<=0){p.hp-=14;p.inv=.85;e.wind=0;g.shake=14;g.hitstop=.055;burst(p.x,p.y,'#d65757',18);tone('hurt',sound);if(p.hp<=0){g.over=true;setHud(h=>({...h,dead:true}))}}});
    g.shots.forEach(s=>g.enemies.forEach(e=>{if(s.life>0&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+6){s.life=0;e.hp-=mage.id==='orlo'?2:1;e.hit=.12;g.hitstop=.025;g.shake=4;burst(e.x,e.y,mage.color,10);tone('hit',sound);if(mage.id==='siv'){e.x-=(p.x-e.x)*.08;e.y-=(p.y-e.y)*.08}if(e.hp<=0){e.dead=true;g.kills++;g.hitstop=.06;burst(e.x,e.y,'#e7d18a',18);if(Math.random()<.8)g.beans.push({x:e.x,y:e.y,t:0})}}}));
    g.enemies=g.enemies.filter(e=>!e.dead);g.shots=g.shots.filter(s=>s.life>0);
    g.beans.forEach(b=>{b.t+=dt;if(Math.hypot(p.x-b.x,p.y-b.y)<36){b.got=true;burst(b.x,b.y,'#f0d66f',12);tone('bean',sound);if(mage.id==='mara')p.hp=Math.min(100,p.hp+5)}});g.beans=g.beans.filter(b=>!b.got);g.particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.92;q.vy*=.92;q.life-=dt});g.particles=g.particles.filter(q=>q.life>0);g.shake=Math.max(0,g.shake-dt*28);
    if(!g.enemies.length){if(g.wave>=3){g.over=true;setHud(h=>({...h,won:true,beans:g.kills}))}else{g.wave++;spawn()}}
    setHud({hp:Math.max(0,Math.round(p.hp)),beans:g.kills,wave:g.wave,spell:g.wave===1?mage.spell:g.wave===2?mage.spell+' + Echo':mage.spell+' + Echo + Split',dead:false,won:false,dash:Math.min(100,Math.max(0,(1-p.dash/2.2)*100))});
  }
  draw(x,g,mage);raf=requestAnimationFrame(step)}raf=requestAnimationFrame(step);
  return()=>{cancelAnimationFrame(raf);removeEventListener('keydown',kd);removeEventListener('keyup',ku);c.removeEventListener('mousemove',mm);c.removeEventListener('mousedown',shoot)}
 },[mage]);
 return <div className="game-shell"><header><button className="text-btn" onClick={onExit}>← abandon run</button><div className="brand">BEANVAULT <small>ROOM I · THE SUNKEN LARDER</small></div><div className="mage-id"><button className="sound" aria-label="Toggle sound" onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}</button><span style={{color:mage.color}}>{mage.icon}</span>{mage.name}</div></header><main className="play"><canvas ref={canvas} width="900" height="620"/><div className="vignette"/><aside className="hud-left"><label>VITAL ESSENCE</label><div className="bar"><i style={{width:hud.hp+'%'}}/></div><b>{hud.hp}</b><label>DODGE</label><div className="bar dash"><i style={{width:hud.dash+'%'}}/></div></aside><aside className="hud-right"><div className="bean">◉ <b>{hud.beans}</b><span>moon beans</span></div><div className="wave">WAVE <b>{hud.wave}/3</b></div></aside><div className="spell-card"><small>ACTIVE CONJURATION</small><strong><Sparkles size={16}/>{hud.spell}</strong><span>left click to cast</span></div><div className="controls"><b>WASD</b> move <b>SPACE</b> dodge <b>CLICK</b> cast</div>{(hud.dead||hud.won)&&<div className="result"><span>{hud.won?'THE VAULT YIELDS':'THE INK RUNS DRY'}</span><h2>{hud.won?'Harvest complete.':'Your mage has fallen.'}</h2><p>{hud.won?`You carried ${hud.beans} moon beans out of the larder.`:'Watch the red attack ring. Dodge through the strike.'}</p><button onClick={()=>location.reload()}><RotateCcw size={16}/> begin another run</button></div>}</main></div>
}

function draw(x,g,mage){x.save();let sx=(Math.random()-.5)*g.shake,sy=(Math.random()-.5)*g.shake;x.translate(sx,sy);let floor=x.createRadialGradient(450,310,40,450,310,540);floor.addColorStop(0,'#283027');floor.addColorStop(1,'#0e110e');x.fillStyle=floor;x.fillRect(-20,-20,940,660);x.strokeStyle='#333b32';x.lineWidth=1;for(let j=0;j<13;j++)for(let i=0;i<19;i++){let ox=(j%2)*24,px=i*48+ox,py=j*48;x.strokeRect(px+2,py+2,44,44)}
 for(let i=0;i<36;i++){let px=(i*137)%880+10,py=(i*83)%600+10;x.fillStyle=`rgba(210,202,160,${.025+.02*Math.sin(g.time+i)})`;x.beginPath();x.arc(px,py,1+(i%3),0,7);x.fill()}
 x.strokeStyle='#756649';x.lineWidth=5;x.strokeRect(18,18,864,584);x.strokeStyle='#b7a66a55';x.lineWidth=1;x.strokeRect(27,27,846,566);[[140,130],[755,140],[160,500],[740,480]].forEach(([a,b],i)=>{x.fillStyle='#232821';x.fillRect(a-35,b-25,70,50);x.strokeStyle='#515747';x.strokeRect(a-35,b-25,70,50);let f=9+Math.sin(g.time*7+i)*3;x.shadowBlur=18;x.shadowColor='#ee9b47';x.fillStyle='#e6a14d';x.beginPath();x.moveTo(a,b-8-f);x.quadraticCurveTo(a+12,b-4,a,b+5);x.quadraticCurveTo(a-12,b-4,a,b-8-f);x.fill();x.shadowBlur=0});
 g.beans.forEach(b=>{let bob=Math.sin(b.t*5)*4;x.shadowBlur=22;x.shadowColor='#f0d66f';x.fillStyle='#f0d66f';x.beginPath();x.ellipse(b.x,b.y+bob,7,11,.5,0,7);x.fill();x.strokeStyle='#fff5b5';x.beginPath();x.arc(b.x,b.y+bob,14+Math.sin(b.t*4)*3,0,7);x.stroke()});
 x.lineCap='round';g.shots.forEach(s=>{x.shadowBlur=16;x.shadowColor=mage.color;x.strokeStyle=mage.color;x.lineWidth=4;x.beginPath();x.moveTo(s.px,s.py);x.lineTo(s.x,s.y);x.stroke();x.fillStyle='#fffbd7';x.beginPath();x.arc(s.x,s.y,5,0,7);x.fill()});x.shadowBlur=0;
 g.enemies.forEach(e=>{if(e.wind>.25){x.strokeStyle=`rgba(224,73,73,${e.wind})`;x.lineWidth=2+e.wind*3;x.beginPath();x.arc(e.x,e.y,e.r+9+e.wind*8,0,7);x.stroke()}x.save();x.translate(e.x,e.y);let bob=Math.sin(e.pulse*5)*2;x.fillStyle=e.hit>0?'#fff2cf':'#6f465e';x.beginPath();x.moveTo(-e.r,e.r);x.quadraticCurveTo(-e.r*1.2,-e.r*.7,0,-e.r+bob);x.quadraticCurveTo(e.r*1.2,-e.r*.7,e.r,e.r);x.quadraticCurveTo(0,e.r*.5,-e.r,e.r);x.fill();x.fillStyle='#efda9d';x.beginPath();x.arc(-6,-2+bob,2,0,7);x.arc(6,-2+bob,2,0,7);x.fill();x.restore()});
 g.particles.forEach(q=>{x.globalAlpha=Math.max(0,q.life/q.max);x.fillStyle=q.color;x.fillRect(q.x-2,q.y-2,4,4)});x.globalAlpha=1;let p=g.p;x.save();x.translate(p.x,p.y);let aim=Math.atan2(g.mouse.y-p.y,g.mouse.x-p.x);x.rotate(aim);x.shadowBlur=22;x.shadowColor=mage.color;x.fillStyle=mage.color;x.beginPath();x.arc(0,0,13,0,7);x.fill();x.shadowBlur=0;x.fillStyle=p.inv>0?'#fffce8':'#e8ddbf';x.beginPath();x.moveTo(-13,7);x.lineTo(-22,22);x.lineTo(16,15);x.closePath();x.fill();x.strokeStyle='#9f895c';x.lineWidth=4;x.beginPath();x.moveTo(6,0);x.lineTo(27,0);x.stroke();x.restore();x.strokeStyle=mage.color+'88';x.lineWidth=1;x.beginPath();x.arc(g.mouse.x,g.mouse.y,9+Math.sin(g.time*8)*2,0,7);x.moveTo(g.mouse.x-14,g.mouse.y);x.lineTo(g.mouse.x+14,g.mouse.y);x.moveTo(g.mouse.x,g.mouse.y-14);x.lineTo(g.mouse.x,g.mouse.y+14);x.stroke();if(g.banner>0){x.globalAlpha=Math.min(1,g.banner*2);x.fillStyle='#11140dd9';x.fillRect(300,250,300,105);x.strokeStyle='#9f8d56';x.strokeRect(307,257,286,91);x.fillStyle='#d9cc9e';x.textAlign='center';x.font='10px DM Mono';x.fillText('THE VAULT STIRS',450,285);x.font='600 38px Cormorant Garamond';x.fillText(`Wave ${g.wave}`,450,325);x.globalAlpha=1}x.restore()}

function App(){const [selected,setSelected]=useState(null),[sound,setSound]=useState(true);if(selected)return <Game mage={selected} sound={sound} setSound={setSound} onExit={()=>setSelected(null)}/>;return <div className="select"><nav><div className="logo">BEANVAULT <span>an arcane harvest</span></div><button aria-label="Toggle sound" className="sound" onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}</button></nav><section className="intro"><p className="eyebrow">FIELD ENTRY 01 · THE SUNKEN LARDER</p><h1>Choose who enters<br/><em>the hungry dark.</em></h1><p>Three mages. One sealed vault. Gather moon beans, splice forbidden traits into your spell, and make it back with your name intact.</p></section><section className="roster">{MAGES.map((m,i)=><article key={m.id} style={{'--accent':m.color}}><div className="portrait"><span>{m.icon}</span><i>{String(i+1).padStart(2,'0')}</i></div><small>{m.title}</small><h2>{m.name}</h2><p>{m.desc}</p><div className="spell"><Sparkles size={14}/><b>{m.spell}</b></div><button onClick={()=>{tone('wave',sound);setSelected(m)}}>enter as {m.name.split(' ')[0]} <span>→</span></button></article>)}</section><footer><span>FEEL PASS 02 · THREE WAVES</span><span>Every bean remembers the hand that buried it.</span></footer></div>}

createRoot(document.getElementById('root')).render(<App/>);
